/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

/**
 *
 * @author Javier
 */
public class Portada extends javax.swing.JPanel {

    /**
     * Creates new form Portada
     */
    public Portada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_imgPortadan = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_imgPortadan.setBackground(new java.awt.Color(255, 255, 255));
        jL_imgPortadan.setForeground(new java.awt.Color(255, 255, 255));
        jL_imgPortadan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/phineas_y_ferb_juego.png"))); // NOI18N
        jL_imgPortadan.setText("jLabel1");
        jL_imgPortadan.setMaximumSize(new java.awt.Dimension(870, 525));
        jL_imgPortadan.setMinimumSize(new java.awt.Dimension(870, 525));
        jL_imgPortadan.setPreferredSize(new java.awt.Dimension(870, 525));
        add(jL_imgPortadan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_imgPortadan;
    // End of variables declaration//GEN-END:variables
}
